---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r addBasename}

# Add basename column to samplekey.csv file (generated by script)

library(recount)

file_list <- list.files('../input/')
file_list <- file_list[grep(file_list, pattern="GSM")]

base_names <- list.files("../input/", full.names=TRUE)
base_names <- base_names[grep(base_names, pattern="GSM")]
base_names <- gsub('.{12}$', '', base_names)
base_names <- base_names[!duplicated(base_names)]

sample_key <- read.csv(file="../input/samplekey.csv")
sample_key$Basename <- base_names

saveRDS(sample_key, file="../output/data.RDS")

rm(file_list)
rm(base_names)

```

```{r createRGSet}

# Generate RGChannelSet from input data

library(minfi)

targets <- readRDS("../output/data.RDS")
rg_set <- read.metharray.exp(targets = targets)

```