library(recount)
library(minfi)

# Program reads samplekey.csv file generated by
# "downloadGeo" script, adds "Basename" column and
# saves both .csv data and RGChannelSet R objects to
# data.RDS and RGSet files.

# Obtain the file list

file_list <- list.files("input/")
file_list <- file_list[grep(file_list, pattern="GSM")]

# Generate valid base names

base_names <- list.files("input/", full.names=TRUE)
base_names <- base_names[grep(base_names, pattern="GSM")]
base_names <- gsub('.{12}$', '', base_names)
base_names <- base_names[!duplicated(base_names)]

# Add required "Basename" column, save the data

sample_key <- read.csv(file="input/samplekey.csv")
sample_key$Basename <- base_names

saveRDS(sample_key, file="output/data.RDS")

# Generate RGChannelSet from data.RDS, save the RGSet

targets <- readRDS("output/data.RDS")
rg_set <- read.metharray.exp(targets = targets)

saveRDS(rg_set, file="output/RGSet.RDS")